# Generated by Django 5.2.11 on 2026-02-12 03:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('supplier', 'Supplier')], max_length=10)),
                ('country', models.CharField(max_length=2, verbose_name='country')),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemandPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_country', models.CharField(max_length=2, verbose_name='country')),
                ('location_locality', models.CharField(blank=True, max_length=255, verbose_name='city / town')),
                ('location_region', models.CharField(blank=True, max_length=255, verbose_name='state / province')),
                ('location_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('item_text', models.CharField(max_length=500, verbose_name='item description')),
                ('category', models.CharField(blank=True, choices=[('food_fresh', 'Food — Fresh'), ('food_shelf', 'Food — Shelf-stable'), ('botanical', 'Botanical'), ('animal_product', 'Animal product'), ('material', 'Material'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='quantity')),
                ('quantity_unit', models.CharField(blank=True, max_length=50, verbose_name='unit')),
                ('cadence', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring'), ('seasonal', 'Seasonal')], max_length=10)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_allowed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('demand_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.demandpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_threads', to=settings.AUTH_USER_MODEL)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='marketplace.match')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='type')),
                ('country', models.CharField(max_length=2, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demandpost',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_posts', to='marketplace.organization'),
        ),
        migrations.CreateModel(
            name='SupplyLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_country', models.CharField(max_length=2, verbose_name='country')),
                ('location_locality', models.CharField(blank=True, max_length=255, verbose_name='city / town')),
                ('location_region', models.CharField(blank=True, max_length=255, verbose_name='state / province')),
                ('location_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('item_text', models.CharField(max_length=500, verbose_name='item description')),
                ('category', models.CharField(blank=True, choices=[('food_fresh', 'Food — Fresh'), ('food_shelf', 'Food — Shelf-stable'), ('botanical', 'Botanical'), ('animal_product', 'Animal product'), ('material', 'Material'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='quantity')),
                ('quantity_unit', models.CharField(blank=True, max_length=50, verbose_name='unit')),
                ('available_until', models.DateTimeField(verbose_name='available until')),
                ('shipping_options', models.TextField(blank=True, verbose_name='shipping options')),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='asking price')),
                ('price_unit', models.CharField(blank=True, max_length=50, verbose_name='price unit')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='supply_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.supplylot'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('demand_post', 'supply_lot')},
        ),
    ]
