# Generated by Django 5.2.11 on 2026-02-17 14:59

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('supplier', 'Supplier')], max_length=10)),
                ('country', models.CharField(max_length=2, verbose_name='country')),
                ('display_name', models.CharField(default='', max_length=100, verbose_name='display name')),
                ('email_verified', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=63, verbose_name='timezone')),
                ('distance_unit', models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=2, verbose_name='distance unit')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_threads', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='type')),
                ('country', models.CharField(max_length=2, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_country', models.CharField(max_length=2, verbose_name='country')),
                ('location_locality', models.CharField(blank=True, max_length=255, verbose_name='city / town')),
                ('location_region', models.CharField(blank=True, max_length=255, verbose_name='state / province')),
                ('location_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('item_text', models.CharField(max_length=500, verbose_name='item description')),
                ('category', models.CharField(blank=True, choices=[('food_fresh', 'Food — Fresh'), ('food_shelf', 'Food — Shelf-stable'), ('botanical', 'Botanical'), ('animal_product', 'Animal product'), ('material', 'Material'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('quantity_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity')),
                ('quantity_unit', models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20, verbose_name='unit')),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring'), ('seasonal', 'Seasonal')], max_length=10)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_allowed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_posts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_posts', to='marketplace.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_country', models.CharField(max_length=2, verbose_name='country')),
                ('location_locality', models.CharField(blank=True, max_length=255, verbose_name='city / town')),
                ('location_region', models.CharField(blank=True, max_length=255, verbose_name='state / province')),
                ('location_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('item_text', models.CharField(max_length=500, verbose_name='item description')),
                ('category', models.CharField(blank=True, choices=[('food_fresh', 'Food — Fresh'), ('food_shelf', 'Food — Shelf-stable'), ('botanical', 'Botanical'), ('animal_product', 'Animal product'), ('material', 'Material'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('quantity_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity')),
                ('quantity_unit', models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20, verbose_name='unit')),
                ('available_until', models.DateTimeField(verbose_name='available until')),
                ('shipping_scope', models.CharField(choices=[('local_only', 'Local pickup only'), ('domestic', 'Anywhere in my country'), ('north_america', 'US, Canada & Mexico'), ('international', 'Worldwide')], default='local_only', max_length=20, verbose_name='shipping scope')),
                ('asking_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='asking price')),
                ('price_unit', models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20, verbose_name='price unit')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('starred', 'Starred'), ('watching', 'Watching'), ('archived', 'Archived')], default='watching', max_length=10)),
                ('source', models.CharField(choices=[('suggestion', 'Suggestion'), ('search', 'Search'), ('direct', 'Direct')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='marketplace.demandpost')),
                ('supply_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='marketplace.supplylot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='messagethread',
            name='watchlist_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='marketplace.watchlistitem'),
        ),
        migrations.CreateModel(
            name='DismissedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.demandpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('supply_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.supplylot')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('demand_post__isnull', True), ('supply_lot__isnull', False)), models.Q(('demand_post__isnull', False), ('supply_lot__isnull', True)), _connector='OR'), name='dismissed_exactly_one_listing'), models.UniqueConstraint(condition=models.Q(('supply_lot__isnull', False)), fields=('user', 'supply_lot'), name='unique_dismissed_supply_lot'), models.UniqueConstraint(condition=models.Q(('demand_post__isnull', False)), fields=('user', 'demand_post'), name='unique_dismissed_demand_post')],
            },
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('demand_post__isnull', True), ('supply_lot__isnull', False)), models.Q(('demand_post__isnull', False), ('supply_lot__isnull', True)), _connector='OR'), name='watchlist_exactly_one_listing'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('supply_lot__isnull', False)), fields=('user', 'supply_lot'), name='unique_user_supply_lot'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('demand_post__isnull', False)), fields=('user', 'demand_post'), name='unique_user_demand_post'),
        ),
    ]
