# Generated by Django 5.2.11 on 2026-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance_unit',
            field=models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=2, verbose_name='distance unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=63, verbose_name='timezone'),
        ),
    ]
