# Generated by Django 5.2.11 on 2026-02-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skin',
            field=models.CharField(choices=[('warm-editorial', 'Warm Editorial'), ('simple-blue', 'Simple Blue')], default='warm-editorial', max_length=20, verbose_name='theme'),
        ),
    ]
