# Generated by Django 5.2.11 on 2026-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_user_distance_unit_user_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandpost',
            old_name='cadence',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='supplylot',
            name='shipping_options',
        ),
        migrations.AddField(
            model_name='supplylot',
            name='shipping_scope',
            field=models.CharField(choices=[('local_only', 'Local only'), ('domestic', 'Domestic'), ('north_america', 'North America'), ('international', 'International')], default='local_only', max_length=20, verbose_name='shipping scope'),
        ),
        migrations.AlterField(
            model_name='demandpost',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='demandpost',
            name='quantity_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='supplylot',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20, verbose_name='price unit'),
        ),
        migrations.AlterField(
            model_name='supplylot',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='supplylot',
            name='quantity_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
