# Generated by Django 5.2.11 on 2026-02-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_cadence_demandpost_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=100, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='supplylot',
            name='asking_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='asking price'),
        ),
        migrations.AlterField(
            model_name='supplylot',
            name='shipping_scope',
            field=models.CharField(choices=[('local_only', 'Local pickup only'), ('domestic', 'Anywhere in my country'), ('north_america', 'US, Canada & Mexico'), ('international', 'Worldwide')], default='local_only', max_length=20, verbose_name='shipping scope'),
        ),
    ]
