# Generated by Django 5.2.11 on 2026-02-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_user_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplylot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
