# Generated by Django 5.2.11 on 2026-02-16 00:49

from django.db import migrations


def populate_display_name(apps, schema_editor):
    User = apps.get_model("marketplace", "User")
    for user in User.objects.filter(display_name=""):
        user.display_name = user.email.split("@")[0]
        user.save(update_fields=["display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_user_display_name_alter_supplylot_asking_price_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_display_name, migrations.RunPython.noop),
    ]
