# Generated by Django 5.2.11 on 2026-02-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_threadreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_on_message',
            field=models.BooleanField(default=False, verbose_name='email me when I receive a message'),
        ),
    ]
