# Generated by Django 5.2.11 on 2026-03-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_add_email_on_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('listing', 'Listing'), ('thread', 'Thread'), ('watchlist', 'Watchlist')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('target_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'source_pk'], name='marketplace_entity__405243_idx'), models.Index(fields=['status', 'migrated_at'], name='marketplace_status_dbe875_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegacyToTargetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('listing', 'Listing'), ('thread', 'Thread'), ('watchlist', 'Watchlist')], max_length=20)),
                ('legacy_pk', models.PositiveIntegerField()),
                ('target_pk', models.PositiveIntegerField()),
                ('mapping_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'legacy_pk'), name='unique_legacy_to_target_mapping')],
            },
        ),
        migrations.CreateModel(
            name='MigrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('mode', models.CharField(choices=[('legacy', 'Legacy'), ('compatibility', 'Compatibility'), ('target', 'Target')], default='legacy', max_length=20)),
                ('stage', models.CharField(choices=[('schema', 'Schema'), ('backfill', 'Backfill'), ('compat', 'Compatibility'), ('cutover', 'Cutover'), ('cleanup', 'Cleanup')], default='schema', max_length=20)),
                ('checkpoint', models.CharField(default='CP0', max_length=10)),
                ('checkpoint_order', models.PositiveSmallIntegerField(default=0)),
                ('dual_write_enabled', models.BooleanField(default=False)),
                ('dual_read_enabled', models.BooleanField(default=False)),
                ('read_canonical', models.CharField(choices=[('legacy', 'Legacy'), ('target', 'Target')], default='legacy', max_length=10)),
                ('write_canonical', models.CharField(choices=[('legacy', 'Legacy'), ('target', 'Target')], default='legacy', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('checkpoint_order__gte', 0), ('checkpoint_order__lte', 5)), name='migration_state_checkpoint_order_bounds')],
            },
        ),
        migrations.CreateModel(
            name='ParityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('schema', 'Schema'), ('backfill', 'Backfill'), ('compat', 'Compatibility'), ('cutover', 'Cutover'), ('cleanup', 'Cleanup')], max_length=20)),
                ('scope', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=False)),
                ('total_checked', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('failure_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['stage', 'scope', 'generated_at'], name='marketplace_stage_f579a1_idx'), models.Index(fields=['passed', 'generated_at'], name='marketplace_passed_dd79cd_idx')],
            },
        ),
    ]
