# Generated by Django 5.2.11 on 2026-03-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_backfillauditrecord_legacytotargetmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='organization name'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_country', models.CharField(max_length=2, verbose_name='country')),
                ('location_locality', models.CharField(blank=True, max_length=255, verbose_name='city / town')),
                ('location_region', models.CharField(blank=True, max_length=255, verbose_name='state / province')),
                ('location_postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('type', models.CharField(choices=[('supply', 'Supply'), ('demand', 'Demand')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('food_fresh', 'Food — Fresh'), ('food_shelf', 'Food — Shelf-stable'), ('botanical', 'Botanical'), ('animal_product', 'Animal product'), ('material', 'Material'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=3)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20)),
                ('price_unit', models.CharField(blank=True, choices=[('Weight', [('lb', 'Pounds (lb)'), ('oz', 'Ounces (oz)'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('ton_short', 'Short tons'), ('ton_metric', 'Metric tons')]), ('Volume', [('gal', 'Gallons (gal)'), ('qt', 'Quarts (qt)'), ('l', 'Liters (L)'), ('ml', 'Milliliters (mL)'), ('fl_oz', 'Fluid ounces (fl oz)'), ('bbl', 'Barrels (bbl)')]), ('Length', [('ft', 'Feet (ft)'), ('yd', 'Yards (yd)'), ('m', 'Meters (m)'), ('in', 'Inches (in)'), ('cm', 'Centimeters (cm)')]), ('Agriculture', [('bu', 'Bushels (bu)'), ('bale', 'Bales'), ('cord', 'Cords')]), ('Count', [('each', 'Each'), ('dz', 'Dozen (dz)'), ('gross', 'Gross'), ('pk', 'Pack'), ('pair', 'Pair')]), ('Container', [('case', 'Case'), ('crate', 'Crate'), ('box', 'Box'), ('carton', 'Carton'), ('bag', 'Bag'), ('sack', 'Sack'), ('pallet', 'Pallet'), ('bundle', 'Bundle')]), ('Textile', [('bolt', 'Bolt'), ('roll', 'Roll')]), ('Lumber', [('bd_ft', 'Board feet (bd ft)'), ('sheet', 'Sheet'), ('cu_yd', 'Cubic yards'), ('cu_m', 'Cubic meters')]), ('General', [('unit', 'Unit'), ('load', 'Load'), ('lot', 'Lot'), ('other', 'Other')])], max_length=20)),
                ('shipping_scope', models.CharField(blank=True, choices=[('local_only', 'Local pickup only'), ('domestic', 'Domestic'), ('north_america', 'North America'), ('worldwide', 'Worldwide')], max_length=20)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('one_time', 'One-time'), ('recurring', 'Recurring'), ('seasonal', 'Seasonal')], max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_source_type', models.CharField(blank=True, max_length=20)),
                ('legacy_source_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_created_threads', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_threads', to='marketplace.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingWatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('starred', 'Starred'), ('watching', 'Watching'), ('archived', 'Archived')], default='watching', max_length=10)),
                ('source', models.CharField(choices=[('suggestion', 'Suggestion'), ('search', 'Search'), ('direct', 'Direct')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_watchlist_items', to='marketplace.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_source_pk__isnull', False), ('legacy_source_type__gt', '')), fields=('legacy_source_type', 'legacy_source_pk'), name='unique_listing_legacy_source'),
        ),
        migrations.AddConstraint(
            model_name='listingmessagethread',
            constraint=models.UniqueConstraint(fields=('listing', 'created_by_user'), name='unique_target_thread_per_listing_initiator'),
        ),
        migrations.AddConstraint(
            model_name='listingwatchlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_target_listing_watchlist'),
        ),
    ]
