# Generated by Django 5.2.11 on 2026-03-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_messagethread_created_by_user_messagethread_listing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dismissedsuggestion',
            name='dismissed_exactly_one_listing',
        ),
        migrations.RemoveConstraint(
            model_name='watchlistitem',
            name='watchlist_exactly_one_listing',
        ),
        migrations.AddField(
            model_name='dismissedsuggestion',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_suggestions', to='marketplace.listing'),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='marketplace.listing'),
        ),
        migrations.AddConstraint(
            model_name='dismissedsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('demand_post__isnull', True), ('listing__isnull', False), ('supply_lot__isnull', True)), models.Q(('demand_post__isnull', True), ('listing__isnull', True), ('supply_lot__isnull', False)), models.Q(('demand_post__isnull', False), ('listing__isnull', True), ('supply_lot__isnull', True)), _connector='OR'), name='dismissed_exactly_one_listing'),
        ),
        migrations.AddConstraint(
            model_name='dismissedsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('user', 'listing'), name='unique_dismissed_listing'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('demand_post__isnull', True), ('listing__isnull', False), ('supply_lot__isnull', True)), models.Q(('demand_post__isnull', True), ('listing__isnull', True), ('supply_lot__isnull', False)), models.Q(('demand_post__isnull', False), ('listing__isnull', True), ('supply_lot__isnull', True)), _connector='OR'), name='watchlist_exactly_one_listing'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('user', 'listing'), name='unique_user_listing'),
        ),
    ]
