# Generated by Django 5.2.11 on 2026-03-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_nullable_canonical_rows(apps, schema_editor):
    MessageThread = apps.get_model("marketplace", "MessageThread")
    WatchlistItem = apps.get_model("marketplace", "WatchlistItem")
    DismissedSuggestion = apps.get_model("marketplace", "DismissedSuggestion")

    MessageThread.objects.filter(listing__isnull=True).delete()
    MessageThread.objects.filter(created_by_user__isnull=True).delete()
    WatchlistItem.objects.filter(listing__isnull=True).delete()
    DismissedSuggestion.objects.filter(listing__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_remove_dismissedsuggestion_dismissed_exactly_one_listing_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dismissedsuggestion",
            name="unique_dismissed_supply_lot",
        ),
        migrations.RemoveConstraint(
            model_name="dismissedsuggestion",
            name="unique_dismissed_demand_post",
        ),
        migrations.RemoveConstraint(
            model_name="dismissedsuggestion",
            name="dismissed_exactly_one_listing",
        ),
        migrations.RemoveConstraint(
            model_name="dismissedsuggestion",
            name="unique_dismissed_listing",
        ),
        migrations.RemoveConstraint(
            model_name="messagethread",
            name="unique_message_thread_per_listing_initiator",
        ),
        migrations.RemoveConstraint(
            model_name="watchlistitem",
            name="unique_user_supply_lot",
        ),
        migrations.RemoveConstraint(
            model_name="watchlistitem",
            name="unique_user_demand_post",
        ),
        migrations.RemoveConstraint(
            model_name="watchlistitem",
            name="watchlist_exactly_one_listing",
        ),
        migrations.RemoveConstraint(
            model_name="watchlistitem",
            name="unique_user_listing",
        ),
        migrations.RemoveField(
            model_name="dismissedsuggestion",
            name="demand_post",
        ),
        migrations.RemoveField(
            model_name="dismissedsuggestion",
            name="supply_lot",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="demand_post",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="supply_lot",
        ),
        migrations.RemoveField(
            model_name="messagethread",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="messagethread",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="messagethread",
            name="watchlist_item",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RunPython(cleanup_nullable_canonical_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="listing",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_message_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_threads",
                to="marketplace.listing",
            ),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_items",
                to="marketplace.listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="dismissedsuggestion",
            constraint=models.UniqueConstraint(fields=("user", "listing"), name="unique_dismissed_listing"),
        ),
        migrations.AddConstraint(
            model_name="messagethread",
            constraint=models.UniqueConstraint(
                fields=("listing", "created_by_user"),
                name="unique_message_thread_per_listing_initiator",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(fields=("user", "listing"), name="unique_user_listing"),
        ),
        migrations.DeleteModel(name="DemandPost"),
        migrations.DeleteModel(name="ListingMessageThread"),
        migrations.DeleteModel(name="ListingWatchlistItem"),
        migrations.DeleteModel(name="Organization"),
        migrations.DeleteModel(name="SupplyLot"),
    ]
