# Generated by Django 5.2.11 on 2026-03-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_demandpost_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_listing_legacy_source',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='legacy_source_pk',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='legacy_source_type',
        ),
    ]
