# Generated by Django 5.2.11 on 2026-03-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
