# Generated by Django 5.2.11 on 2026-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_add_profile_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enter_to_send',
            field=models.BooleanField(default=False, verbose_name='press Enter to send messages'),
        ),
    ]
